# Generated by Django 5.1.7 on 2025-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloCursos', models.CharField(max_length=64)),
                ('instituicaoCursos', models.CharField(max_length=64)),
                ('anoCursos', models.IntegerField()),
                ('descriçãoCursos', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descricaoProjetos', models.CharField(max_length=1000)),
                ('linkProjetos', models.URLField()),
                ('tecnologiasProjetos', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeRecados', models.CharField(max_length=64)),
                ('assuntoRecados', models.CharField(max_length=64)),
                ('emailRecados', models.EmailField(max_length=254)),
                ('mensagemRecados', models.CharField(max_length=1000)),
                ('dataRecados', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
