# Generated by Django 5.1.7 on 2025-08-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='descriçãoCursos',
            new_name='descricaoCursos',
        ),
    ]
