# Generated by Django 5.1.7 on 2025-08-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_descriçãocursos_cursos_descricaocursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetos',
            old_name='titulo',
            new_name='tituloProjetos',
        ),
    ]
