# Generated by Django 5.1.7 on 2025-08-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_rename_titulo_projetos_tituloprojetos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Projetos',
        ),
    ]
